
linkshelltls:
	cc -o tls ../filesystem/models.c ../filesystem/utils.c ../filesystem/directory.c tls.c

linkshelltcreate:
	cc -o tcreate ../filesystem/models.c ../filesystem/utils.c ../filesystem/create.c tcreate.c

linkshelltdelete:
	cc -o tdelete ../filesystem/models.c ../filesystem/utils.c ../filesystem/delete.c tdelete.c

linkshellwrite:
	cc -o twrite ../filesystem/models.c ../filesystem/utils.c ../filesystem/directory.c ../filesystem/write.c twrite.c

linkshellread:
	cc -o tread	../filesystem/models.c ../filesystem/utils.c ../filesystem/directory.c ../filesystem/read.c tread.c

linkshellchname:
	cc -o tchname ../filesystem/models.c ../filesystem/utils.c ../filesystem/directory.c tchname.c 
